title: "/dev/blog/ID10T"
author: "m3adow"
description: "Because /dev/random is too predictable."
# subheading: "Because /dev/random is too predictable."
more: "read more"
url: "https://adminswerk.de"
# baseurl: "/contrast" # comment out if in root directory
permalink: /:title/

collections_dir: collect_all_the_things

collections:
  category:
    output: true

future: false
comments:
  isso: "comments.tillwiese.de/adminswerk.de.fcgi"

lang: en_US

style:
  # body: "whitesmoke"
  padding: 33%
  anchor: "#46f"
  serif-heading: false
  nav: "#181818"
  # headline: "#06f"
  description: "white"
  article:
    odd: "#fff"
    # even: "#fff"

paginate: 5
paginate_path: "/older/page:num"

links:
  - github: "https://github.com/m3adow/"
  - bitbucket: "https://bitbucket.org/m3adow/"
  - xing: "https://www.xing.com/profile/Till_Wiese"
  - linkedin: "https://www.linkedin.com/pub/till-wiese/46/403/7b4"

excerpt_separator: "<!--more-->"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-seo-tag
